### ISSUE TITLE
Removed HTTP helper to load states?

### ISSUE THREAD

**Issue by benlwong** [DougSisk/laravel-country-state#10]
Apparently, for 2.0 version, the URL country-state/get-states to fetch states for a country was removed. Is this correct? We will now have to write our own?

**Comment by DougSisk** [comment]
Yes, it was removed because I decided everyone probably has their own opinions on how to go about returning a JSON response. Also wasn't aware anyone was actually using it, so sorry for that.

**Comment by benlwong** [comment]
No worries. I just recreated it myself.
