### ISSUE TITLE
ISO Code to full name for States and Country

### ISSUE THREAD

**Issue by Ashubgs90** [DougSisk/laravel-country-state#11]
I need to get Country or State full name form **ISO Code**

some thing llike this:- 

`$countryName = CountryState::getCountryName('US');`

then `$countryName` will have value United States, and same for StateName.

Is there any way to get that here.

**Comment by DougSisk** [comment]
I just tagged 2.1 which adds 2 methods: `getCountry()` and `getCountryName()`. `getStateName()` was already available.

**Comment by Ashubgs90** [comment]
`getStateName()` work fine only, when we pass countryCode also, else it is returning first matched value to state ISO. I guess it has to return all matched value.

**Comment by khelsisura** [comment]
How to change the iso value into real country name?

**Comment by harveyelsisura** [comment]
```The array keys will be the countries' 2 letter ISO code and the values will be the countries' English name. You may also set the 3 letter ISO key as the argument to receive translations of the countries' names (limited support).```

How? lol
