### ISSUE TITLE
Underlying package abandoned

### ISSUE THREAD

**Issue by ragingdave** [DougSisk/laravel-country-state#12]
Just got this notice on my last composer update:
Package rinvex/country is abandoned, you should avoid using it. Use rinvex/countries instead.

**Comment by DougSisk** [comment]
Thanks for informing me. It looks like the package was simply renamed. I'll push a quick fix to rename the package. The package is up to 5.0 now, but it requires PHP 7.1.3+ which means only Laravel 5.6+ can be supported. I'll have to tag a major release for that.
