### ISSUE TITLE
Problem installing with Laravel 6.0.1

### ISSUE THREAD

**Issue by haratmalli** [DougSisk/laravel-country-state#17]
Problem 1
    - Conclusion: don't install dougsisk/laravel-country-state 2.1.1
    - Conclusion: remove laravel/framework v6.0.1
    - Installation request for dougsisk/laravel-country-state ^2.1 -> satisfiable by dougsisk/laravel-country-state[2.1, 2.1.1].
    - Conclusion: don't install laravel/framework v6.0.1

**Comment by DougSisk** [comment]
Laravel 6.0 support is only available with 3.0. I released it last night, but Packagist apparently didn't pick up on the release. It's been updated now.
