### ISSUE TITLE
It is not working on lumen 8.X

### ISSUE THREAD

**Issue by Talented-Business** [DougSisk/laravel-country-state#18]
I installed this package and add "$app->register(DougSisk\CountryState\CountryStateServiceProvider::class);" on bootstrap/app.php.
And it shows following errors.
![countryState issue](https://user-images.githubusercontent.com/2536597/95673238-e73cca00-0be1-11eb-88b5-b3620dd90659.png)

**Comment by Talented-Business** [comment]
Did you solve this issue?

**Comment by DougSisk** [comment]
I do not support Lumen, sorry.
