### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by derikitz** [DougSisk/laravel-country-state#2]
Something is not right...

Nothing happens on the 3rd step,
where you do
`php artisan vendor:publish`

**Comment by DougSisk** [comment]
Make sure if you have config caching on to clear it after adding the service provider into the config.

Also try running this as another package's provider might be preventing the `vendor:publish` command from running properly:
`php artisan vendor:publish --provider="DougSisk\CountryState\CountryStateServiceProvider"`

**Comment by derikitz** [comment]
I see.. I'll try that..
