### ISSUE TITLE
The state ISO2 codes are old. 

### ISSUE THREAD

**Issue by sathiyad** [DougSisk/laravel-country-state#24]
The states ISO2 codes are not updated with the new ISO2 code. 
for example 
Country: China 
State / Prov.: Beijing Shi
The  **CountryState** returning the code as 11, but it`s already updated to BJ
So the package is throwing exception while getting the state name by BJ.

**Comment by DougSisk** [comment]
Sorry, I don't control the data. That's all in [another package](https://github.com/rinvex/countries) that's not mine.
