### ISSUE TITLE
Where is the data stored?

### ISSUE THREAD

**Issue by marlongichie** [DougSisk/laravel-country-state#28]
Hello, can you inform if the data is stored locally in a file somewhere in the package or is it being fetched from an API?

What is the source of the data being returned?

Thank you.

**Comment by KaiRo-at** [comment]
Looks like it comes from rinvex/countries and that one unfortunately has not seen changes for more than a year even though there are open pull requests and issues.

**Comment by DougSisk** [comment]
You're welcome to fork and use a different data source.
