### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by larsjanssen6** [DougSisk/laravel-country-state#9]
Great package!

One quick question. When I've linked a country code (for example us or gb)
to a users table.

How would I eager load the country?

Thanks a lot!

**Comment by DougSisk** [comment]
You would need to create either a method or [an accessor](https://laravel.com/docs/5.4/eloquent-mutators#defining-an-accessor) yourself. Eager loading is only available to Eloquent relationships.

**Comment by larsjanssen6** [comment]
Thanks @DougSisk
